### PR TITLE
fix: allow gitlabUrl without scheme

### LINKED ISSUE #360: Plugin fails with ERR_INVALID_URL since NO_PROXY uses a ULR parser
**Report**
Since version v9.1.0 of the gitlab plugin for semantic-release the plugin fails with an error. The introduction of NO_PROXY support in v9.1.0 contains a new URL parser (see https://github.com/semantic-release/gitlab/commit/3051799160efc127585d30a4ef776ccf34185fee#diff-3c41bd6e7d07732417abb44146ae10fa613e5d61d5df96d088e44cb8d5dc557fR66)  which now fails for urls without a protocol defined. This used to work so far.

**Steps to reproduce**
1. Install version v9.1.0 of gitlab semantic release plugin
2. Set envrionment variable `GITLAB_URL` to `gitlab.my-company.ch` (without https Prefix)
3. Start the semantic-release versioning job
4. The job fails with the error message `An error occurred while running semantic-release: TypeError [ERR_INVALID_URL]: Invalid URL`

**Affected Version**
v9.1.0 (https://github.com/semantic-release/gitlab/releases/tag/v9.1.0)

**Reason**
NO_PROXY feature now uses a url parser (new URL(...)) which fails for GITLAB_URL variables that contain a gitlab url without protocol prefixes. Can be easily reproduced with F12 dev-tools.

**Workaround**
Removing `GITLAB_URL` variable as part of our gitlab-ci.yaml configuration solves this issue since the gitlab plugin falls back to the gitlab's runner url provided through default variables.

### PR DESCRIPTION
**Pull request by Babbafett**
Fixes #360

### CODE REVIEW

File: lib/resolve-config.js [hunk 1]
```diff
@@ -63,7 +63,13 @@ function shouldProxy(gitlabUrl, NO_PROXY) {
...
     wss: 443,
   };
-  const parsedUrl = typeof gitlabUrl === 'string' ? new URL(gitlabUrl) : gitlabUrl || {};
+  let parsedUrl = '';
+  if (gitlabUrl.startsWith('http://') || gitlabUrl.startsWith('https://')) {
+    parsedUrl = typeof gitlabUrl === 'string' ? new URL(gitlabUrl) : gitlabUrl || {};
+  } else {
+    return false; // Never proxy if scheme is not set.
+  }
+
```
Comment (fgreinacher) [inline lib/resolve-config.js:72]:
```suggestion
  const parsedUrl = typeof gitlabUrl === 'string' &&(gitlabUrl.startsWith('http://') || gitlabUrl.startsWith('https://')) ? new URL(gitlabUrl) : gitlabUrl || {};
```

File: lib/resolve-config.js [hunk 2]
```diff
@@ -63,7 +63,7 @@ function shouldProxy(gitlabUrl, NO_PROXY) {
     ws: 80,
     wss: 443,
   };
-  const parsedUrl = typeof gitlabUrl === 'string' ? new URL(gitlabUrl) : gitlabUrl || {};
+  const parsedUrl = typeof gitlabUrl === 'string' &&(gitlabUrl.startsWith('http://') || gitlabUrl.startsWith('https://')) ? new URL(gitlabUrl) : gitlabUrl || {};
```
Comment (fgreinacher) [inline lib/resolve-config.js:66]:
```suggestion
  const parsedUrl =
    typeof gitlabUrl === 'string' &&(gitlabUrl.startsWith('http://') || gitlabUrl.startsWith('https://'))
      ? new URL(gitlabUrl)
      : gitlabUrl || {};
```

File: lib/resolve-config.js [hunk 3]
```diff
@@ -63,7 +63,10 @@ function shouldProxy(gitlabUrl, NO_PROXY) {
     ws: 80,
     wss: 443,
   };
-  const parsedUrl = typeof gitlabUrl === 'string' ? new URL(gitlabUrl) : gitlabUrl || {};
+  const parsedUrl =
+    typeof gitlabUrl === 'string' &&(gitlabUrl.startsWith('http://') || gitlabUrl.startsWith('https://'))
```
Comment (fgreinacher) [inline lib/resolve-config.js:67]:
```suggestion
    typeof gitlabUrl === 'string' && (gitlabUrl.startsWith('http://') || gitlabUrl.startsWith('https://'))
```

**Review by fgreinacher — APPROVED** [review]
Thanks for taking care of this!
