### PR TITLE
fix: display default icons and fix URL in success message

### LINKED ISSUE #344: successComment has bad formatted emojis
Hello.

There should be a space between `:package:` and `:rocket` because they are not displayed on my 14.6 self hosted gitlab.

semantic-release-gitlab-successComment-emoji-fail

Thanks.

### PR DESCRIPTION
**Pull request by JonasSchubert**
First of all thanks to @fgreinacher for this nice feature.
We are using it already and I stumpled upon two issues:
- the :package: and :rocket: icon were not proberly displayed as they were not separated
- the URL to the release did not work because of `%2F` in the URI; this is why I added the `decodeURIComponent`

Fixes #344

### CODE REVIEW

File: lib/get-success-comment.js [hunk 1]
```diff
@@ -7,11 +7,11 @@ module.exports = (issueOrMergeRequest, releaseInfos, nextRelease) =>
     nextRelease.version
   } :tada:${
     releaseInfos.length > 0
-      ? `\n\nThe release is available on${
+      ? `\n\nThe release is available on${decodeURIComponent(
```
Comment (fgreinacher) [inline lib/get-success-comment.js:10]: I think we should rather fix this at https://github.com/semantic-release/gitlab/blob/master/lib/publish.js#L121:

```js
   const releaseUrl = urlJoin(gitlabUrl, repoId, `/-/releases/${encodedGitTag}`);
```

**Comment by fgreinacher** [comment]
Thanks a lot @JonasSchubert! Left a suggestion for you :)

File: lib/get-success-comment.js (hunk 1 above)
Comment (JonasSchubert) [reply lib/get-success-comment.js:10]: Thanks. Good hint. Will check tomorrow.

Comment (JonasSchubert) [reply lib/get-success-comment.js]: Decoding the final release URL now. Should not affect any dependent functionality.

File: test/success.test.js [hunk 2]
```diff
@@ -48,14 +48,14 @@ test.serial('Post comments to related issues and MRs', async t => {
     .reply(200, [])
     .post(`/projects/100/merge_requests/1/notes`, {
       body:
-        ':tada: This MR is included in version 1.0.0 :tada:\n\nThe release is available on [GitLab release](https://gitlab.com/test_user%2Ftest_repo/-/releases/v1.0.0)\nYour **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:',
+        ':tada: This MR is included in version 1.0.0 :tada:\n\nThe release is available on [GitLab release](https://gitlab.com/test_user%2Ftest_repo/-/releases/v1.0.0)\nYour **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package: :rocket:',
```
Comment (fgreinacher) [inline test/success.test.js:51]: The URL here still looks wrong: `https://gitlab.com/test_user%2Ftest_repo/-/releases/v1.0.0`

Comment (JonasSchubert) [reply test/success.test.js:51]: I think because we don't call the publish method with the method `decodeUriComponent`. We mock the created releases in this test. Will adapt the test data to avoid confusion.

File: lib/publish.js [hunk 3]
```diff
@@ -118,7 +118,7 @@ module.exports = async (pluginConfig, context) => {
 
   logger.log('Published GitLab release: %s', gitTag);
 
-  const releaseUrl = urlJoin(gitlabUrl, encodedRepoId, `/-/releases/${encodedGitTag}`);
+  const releaseUrl = decodeURIComponent(urlJoin(gitlabUrl, encodedRepoId, `/-/releases/${encodedGitTag}`));
```
[the remark this answers is not in the document]
Comment (fgreinacher) [reply lib/publish.js:121]: I think `repoId` is already extracted from an URL, in which case we could just take it as-is here.

File: test/success.test.js (hunk 2 above)
Comment (fgreinacher) [reply test/success.test.js:51]: Ah, that's indeed very confusing. Would be great if you'd adapt the test data, thanks!

**Comment by fgreinacher** [comment]
@travi Do you have any idea why the tests are not starting anymore?

File: test/success.test.js (hunk 2 above)
Comment (JonasSchubert) [reply test/success.test.js]: Updated unit tests to use decoded URLs

**Comment by JonasSchubert** [comment]
> First-time contributors need a maintainer to approve running workflows.
😄
Has to be approved by another reviewer to run the tests

**Review by fgreinacher — APPROVED** [review]
LGTM!

**Review by travi — APPROVED** [review]
